import Link from "next/link";
import { logoutAction } from "@/app/actions/auth";
import { Logo } from "@/components/logo";

type Membership = { role: string; organization: { name: string; slug: string } };

export function AppShell({ children, active, memberships }: { children: React.ReactNode; active: Membership; memberships: Membership[] }) {
  const base = `/app/${active.organization.slug}`;
  const canViewMembers = active.role === "OWNER" || active.role === "ADMIN";
  return <div className="min-h-screen"><header className="border-b border-[var(--border)] bg-white"><div className="mx-auto flex min-h-16 max-w-6xl flex-wrap items-center justify-between gap-4 px-5 py-3"><Logo /><div className="flex items-center gap-4"><details className="relative"><summary className="cursor-pointer list-none rounded-xl border border-[var(--border)] px-4 py-2"><span className="block text-sm font-semibold">{active.organization.name}</span><span className="text-xs text-[var(--muted)]">{active.role} · wisselen</span></summary><div className="absolute right-0 z-10 mt-2 w-64 rounded-xl border border-[var(--border)] bg-white p-2 shadow-xl">{memberships.map((item) => <Link className="block rounded-lg px-3 py-2 text-sm hover:bg-slate-50" href={`/app/${item.organization.slug}/dashboard`} key={item.organization.slug}><strong>{item.organization.name}</strong><span className="block text-xs text-[var(--muted)]">{item.role}</span></Link>)}<div className="my-2 border-t border-[var(--border)]" /><Link className="block rounded-lg px-3 py-2 text-sm font-semibold text-[#235347] hover:bg-slate-50" href="/onboarding">+ Nieuwe organisatie</Link></div></details><form action={logoutAction}><button className="text-sm font-semibold text-[var(--muted)]" type="submit">Uitloggen</button></form></div></div></header><div className="mx-auto grid max-w-6xl gap-8 px-5 py-8 md:grid-cols-[190px_1fr]"><nav className="space-y-1" aria-label="Organisatie"><Link className="block rounded-lg px-3 py-2 text-sm font-semibold hover:bg-white" href={`${base}/dashboard`}>Dashboard</Link><Link className="block rounded-lg px-3 py-2 text-sm font-semibold hover:bg-white" href={`${base}/settings`}>Instellingen</Link>{canViewMembers && <Link className="block rounded-lg px-3 py-2 text-sm font-semibold hover:bg-white" href={`${base}/settings/members`}>Leden</Link>}</nav><main>{children}</main></div></div>;
}
